services:
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/tmp/prometheus
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.console.libraries=/usr/share/prometheus/console_libraries
    tmpfs:
      - /tmp
    volumes: !override
      - ./deploy/prometheus/prometheus.benchmark.yml:/etc/prometheus/prometheus.yml:ro
      - ./deploy/prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml:ro
